--
-- fc-crypto.lua — Freechains crypto primitives (luasodium)
--
-- Native Lua replacement for fc-crypto.sh (openssl).
-- Uses libsodium via luasodium bindings.
--
-- Primitives:
--   keygen()                — Ed25519 + Curve25519 keypairs
--   pubkey(key)             — raw Ed25519 public key
--   sign(msg, sk)           — Ed25519 detached signature
--   verify(msg, sig, pk)    — verify detached signature
--   shared_key(passphrase)  — derive 32-byte key (BLAKE2b)
--   shared_encrypt(plain, key) — SecretBox encrypt
--   shared_decrypt(blob, key)  — SecretBox decrypt
--   seal_encrypt(plain, pk)    — sealed box encrypt
--   seal_decrypt(cipher, key)  — sealed box decrypt
--

local sodium = require 'luasodium'

local M = {}

-- Generate keypairs for signing and encryption.
-- Returns table with:
--   sign_pk, sign_sk  — Ed25519 (for signatures)
--   box_pk, box_sk    — Curve25519 (for sealed boxes)
function M.keygen ()
    local sign_pk, sign_sk =
        sodium.crypto_sign_keypair()
    local box_pk, box_sk =
        sodium.crypto_box_keypair()
    return {
        sign_pk = sign_pk, sign_sk = sign_sk,
        box_pk  = box_pk,  box_sk  = box_sk,
    }
end

-- Extract raw Ed25519 public key from keypair.
function M.pubkey (key)
    return key.sign_pk
end

-- Sign message with secret key (detached signature).
-- Returns raw signature bytes.
function M.sign (msg, sk)
    return sodium.crypto_sign_detached(msg, sk)
end

-- Verify detached signature.
-- Returns true if valid, false otherwise.
function M.verify (msg, sig, pk)
    return sodium.crypto_sign_verify_detached(
        sig, msg, pk
    )
end

-- Derive a 32-byte symmetric key from a passphrase.
-- Uses BLAKE2b (crypto_generichash) with default output
-- size (32 bytes = crypto_secretbox_KEYBYTES).
function M.shared_key (passphrase)
    return sodium.crypto_generichash(passphrase)
end

-- Symmetric encrypt: SecretBox (XSalsa20-Poly1305).
-- Generates a random 24-byte nonce, prepends it to the
-- ciphertext. Returns nonce || ciphertext (binary).
function M.shared_encrypt (plain, key)
    local nonce = sodium.randombytes_buf(
        sodium.crypto_secretbox_NONCEBYTES
    )
    local cipher = sodium.crypto_secretbox_easy(
        plain, nonce, key
    )
    return nonce .. cipher
end

-- Symmetric decrypt: SecretBox (XSalsa20-Poly1305).
-- Expects nonce || ciphertext (as returned by shared_encrypt).
-- Returns plaintext, or nil if authentication fails.
function M.shared_decrypt (blob, key)
    local nlen = sodium.crypto_secretbox_NONCEBYTES
    local nonce = blob:sub(1, nlen)
    local cipher = blob:sub(nlen + 1)
    return sodium.crypto_secretbox_open_easy(
        cipher, nonce, key
    )
end

-- Asymmetric encrypt: sealed box.
-- Encrypts to a recipient's Curve25519 public key.
-- Ephemeral keypair is generated by libsodium internally.
-- Returns ciphertext (binary).
function M.seal_encrypt (plain, box_pk)
    return sodium.crypto_box_seal(plain, box_pk)
end

-- Asymmetric decrypt: sealed box.
-- Decrypts with recipient's Curve25519 keypair.
-- Returns plaintext, or nil if authentication fails.
function M.seal_decrypt (cipher, key)
    return sodium.crypto_box_seal_open(
        cipher, key.box_pk, key.box_sk
    )
end

return M
